import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
interface AuthState {
	isLoggedIn: boolean;
	loading: boolean;
	user: {
		id: string;
		email: string;
		username?: string;
		avatar?: string;
	} | null;
	error: string | null;
}
// Define the initial state for the authentication slice
const initialState: AuthState = {
	isLoggedIn: false, // Indicates if a user is currently logged in
	user: null, // Stores user information if logged in (e.g., { id: '...', name: '...' })
	loading: false, // True when a login/logout/status check operation is in progress
	error: null // Stores any error messages from authentication attempts
};

// Create a Redux slice for managing user authentication state
const authSlice = createSlice({
	name: 'auth', // The name of the slice
	initialState, // The initial state defined above
	reducers: {
		// Reducer for when a login process starts (e.g., user submits credentials)
		loginStart: (state) => {
			state.loading = true;
			state.error = null;
		},
		// Reducer for a successful login
		loginSuccess: (state, action) => {
			state.loading = false;
			state.isLoggedIn = true;
			state.user = action.payload; // Store user data (e.g., { id: 'user123', email: 'test@example.com' })
			state.error = null;
		},
		// Reducer for a failed login attempt
		loginFailure: (state, action) => {
			state.loading = false;
			state.isLoggedIn = false;
			state.user = null;
			state.error = action.payload; // Store error message
		},
		// Reducer for when a user logs out
		logout: (state) => {
			state.loading = false;
			state.isLoggedIn = false;
			state.user = null;
			state.error = null;
		},
		// Reducer to set the initial login status when the app loads
		// This is typically called after checking localStorage or a session
		setInitialLoginStatus: (state, action) => {
			state.isLoggedIn = action.payload.isLoggedIn;
			state.user = action.payload.user;
			state.loading = false; // Ensure loading is false after initial check
			state.error = null;
		}
	}
});

// Export the actions generated by createSlice
export const { loginStart, loginSuccess, loginFailure, logout, setInitialLoginStatus } = authSlice.actions;

// Export the reducer function to be added to the Redux store
export default authSlice.reducer;

export const logoutUser = createAsyncThunk('auth/logoutUser', async (_, { dispatch, rejectWithValue }) => {
	try {
		const res = await fetch('/api/signout', {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' }
		});

		if (!res.ok) {
			throw new Error('Failed to sign out');
		}

		// Optionally handle response here (like revoking tokens, etc.)
		dispatch(logout()); // Normal reducer to reset state
		return true;
	} catch (error) {
		const errorMessage = error instanceof Error ? error.message : 'Logout failed';
		return rejectWithValue(errorMessage);
	}
});
